# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=--------boundary

--------boundary
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
--------boundary

###

# @name create-transcription
POST http://localhost:3333/videos/dqwdqwdqw/transcription
Content-Type: application/json;

{
  "prompt": "clean architecture, ddd, palavra-chave"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json;

{
  "videoId": "dqwdqwdqw",
  "template": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}'''",
  "temperature": 0.5
}
